name: Generate Helm dependencies, docs and schema

on:
  push:
    branches-ignore:
      - main
    paths:
      - "charts/ciso-assistant-next/**"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Build Dependencies
        run: |
          helm dependency build charts/ciso-assistant-next

      - name: Generate values schema json
        uses: losisin/helm-values-schema-json-action@v1
        with:
          working-directory: charts/ciso-assistant-next
          input: values.yaml

      - name: Generate helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          chart-search-root: charts/ciso-assistant-next

      - name: Commit and push if it changed
        run: |-
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "update helm auto-gen files" || exit 0
          git push
