name: Helm Testing and docs/schema generator

on:
  pull_request:
    paths:
      - "charts/ciso-assistant-next/**"

jobs:
  generate-helm-json-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate values schema json
        uses: losisin/helm-values-schema-json-action@v1
        with:
          working-directory: charts/ciso-assistant-next
          input: values.yaml
          additionalProperties: false
          git-push: true

  generate-helm-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          chart-search-root: charts/ciso-assistant-next
          git-push: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Lint Helm Chart
        run: |
          cd charts
          helm lint ciso-assistant-next
