name: Helm linter

on:
  pull_request:
    paths:
      - "charts/ciso-assistant-next/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Lint Helm Chart
        run: |
          cd charts
          helm lint ciso-assistant-next
